### ISSUE TITLE
Determiner si la base de  données existe

### ISSUE THREAD

**Issue by matteyeux** [white-wolf-project/ragnarok#43]
Ajouter un check pour voir si la base de donnée existe et savoir quel script executer.

Ca devrait se passer comme ça : 
```C
if (mysql_query(con, "CREATE DATABASE ragnarok_bdd"))  {
      fprintf(stderr, "%s\n", mysql_error(con));
      mysql_close(con);
      exit(1);
}
```

On compile le checker comme ceci : 
``` bash
$ gcc sql.c  `mysql_config --cflags --libs` 
```

Ne pas oublier d'installer le paquet `libmysqlclient-dev` . 
La doc : https://dev.mysql.com/doc/refman/5.7/en/c-api-implementations.html

**Comment by eehP** [comment]
Existe deja dans le script python.
Je vais voir si c'est bien de ça dont tu me parle.

**Comment by matteyeux** [comment]
Tu testes bien si la base de données existe, mais c'est aussi à moi de savoir si elle existe pour savoir quel script excuter (`rangarok_bdd.py` ou `xmlparser.py`)

**Comment by eehP** [comment]
Tu voudrais que je te fasse un return de l'état ? Comme ça tu as juste à check si elle est là ou pas.

**Comment by matteyeux** [comment]
Non, je pourrais pas vérifier le retour du code python en C
