### ISSUE TITLE
Besoin des requêtes SQL

### ISSUE THREAD

**Issue by eehP** [white-wolf-project/ragnarok#52]
Qu'avons nous besoin d'afficher sur le site ?
Je peux faire les requêtes correspondantes a vos demandes.

**Comment by matteyeux** [comment]
On affiche toutes les données qu'on récupère sur le avec le XML, on verra au fur et à mesure si il faut en enlever ou en rajouter

**Comment by eehP** [comment]
Pas de demande précise ?? En prévision.

**Comment by matteyeux** [comment]
Non
