### ISSUE TITLE
Travis : tests d'intégration des scripts Python 3

### ISSUE THREAD

**Issue by matteyeux** [white-wolf-project/ragnarok#53]
Il s'agit de mettre en place les tests d'intégration continue avec Travis.

Tout d'abord installer les nouvelles bibliothèques et paquets tels que : 
- mysql-server
- libmysqlclient-dev
-  libmysql++-dev

Il faut aussi installer différents modules pythons que l'ont utilise.

Il faudra ensuite tester les scripts à l'aide d'un fichier XML au préalable généré par le client ragnarok.
On exécutera ensuite les scripts pour créer la base de données et inséré les données du fichier XML dans la bdd.

**Comment by eehP** [comment]
Un script python 3 pour ça  ?? ou en C ??
